--Insert into conditions table
INSERT INTO CONDITION (CONDITION) VALUES ('As new')
INSERT INTO CONDITION (CONDITION) VALUES ('Fine')
INSERT INTO CONDITION (CONDITION) VALUES ('Very good')
INSERT INTO CONDITION (CONDITION) VALUES ('Good')
INSERT INTO CONDITION (CONDITION) VALUES ('Fair')
INSERT INTO CONDITION (CONDITION) VALUES ('Worn')
INSERT INTO CONDITION (CONDITION) VALUES ('Poor')
INSERT INTO CONDITION (CONDITION) VALUES ('Very poor')
INSERT INTO CONDITION (CONDITION) VALUES ('For scrapping')

--insert into roles table
INSERT INTO ROLE (ROLE) VALUES ('Admin')
INSERT INTO ROLE (ROLE) VALUES ('Operator')
INSERT INTO ROLE (ROLE) VALUES ('Reader')

--insert into ratings table
INSERT INTO RATING (RATING) VALUES (1)
INSERT INTO RATING (RATING) VALUES (2)
INSERT INTO RATING (RATING) VALUES (3)
INSERT INTO RATING (RATING) VALUES (4)
INSERT INTO RATING (RATING) VALUES (5)

--insert into users table
INSERT INTO USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, PHONENUMBER, EMAIL, ADDRESS, ROLE_ID, RATING_ID)
VALUES ('Daniel', 'Kostov', 'D_kostov', 'kostovec', '0887565656', 'kostov@gmail.com', 'ul. Kaloqnski 5', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Admin'), (SELECT RATING.ID FROM RATING WHERE RATING = 5))

INSERT INTO USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, PHONENUMBER, EMAIL, ADDRESS, ROLE_ID, RATING_ID)
VALUES ('Boris', 'Petrov', 'slayer55', 'chetqsht22', '0889232323', 'borisp@abv.bg', 'ul. Smolensk 2', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Reader'), (SELECT RATING.ID FROM RATING WHERE RATING = 4))

INSERT INTO USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, PHONENUMBER, EMAIL, ADDRESS, ROLE_ID, RATING_ID)
VALUES ('Valentina', 'Naidenova', 'v_naidenova', 'vale3424', '0887888888', 'v.naid@abv.bg', 'ul. Sv. Petka', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Operator'), (SELECT RATING.ID FROM RATING WHERE RATING = 5))

INSERT INTO USERS (FIRSTNAME, LASTNAME, USERNAME, PASSWORD, PHONENUMBER, EMAIL, ADDRESS, ROLE_ID, RATING_ID)
VALUES ('Ivan', 'Ivanov', 'vankata96', 'vankosumve2', '0889889898', 'vanko@mail.bg', 'ul. Vqrna 11', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Reader'), (SELECT RATING.ID FROM RATING WHERE RATING = 3))

--Insert into books table
INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVALIABLE)
VALUES ('Vlastelina na prustenite', 'G.R.R. Tolkien', 'Fantasy', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'Very good'), 'true')

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVALIABLE)
VALUES ('Pesen za ogun i led', 'G.R.R. Martin', 'Fantasy', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'Fair'), 'false')

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVALIABLE)
VALUES ('Pod igoto', 'Ivan Vazov', 'Roman', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'As new'), 'false')

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVALIABLE)
VALUES ('Tobacco', 'Dimitar Dimov', 'Roman', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'Worn'), 'true')

--insert into issues table
INSERT INTO ISSUE (BOOK_ID, USER_ID, ISSUE_DATE, RETURN_DATE, RETURNED_CONDITION_ID) 
VALUES ((SELECT ID FROM BOOKS WHERE TITLE = 'Pod Igoto'), (SELECT ID FROM USERS WHERE USERNAME = 'slayer55'), getdate(), convert(date,'15-12-20',5), (SELECT ID FROM CONDITION WHERE CONDITION = 'As new'))

INSERT INTO ISSUE (BOOK_ID, USER_ID, ISSUE_DATE, RETURN_DATE, RETURNED_CONDITION_ID) 
VALUES ((SELECT ID FROM BOOKS WHERE TITLE = 'Pesen za ogun i led'), (SELECT ID FROM USERS WHERE USERNAME = 'vankata96'), getdate(), convert(date,'11-12-20',5), (SELECT ID FROM CONDITION WHERE CONDITION = 'Fair'))