USE [LibraryDB]
GO

--Insert into conditions table
INSERT INTO CONDITION (CONDITION) VALUES ('As new')
INSERT INTO CONDITION (CONDITION) VALUES ('Fine')
INSERT INTO CONDITION (CONDITION) VALUES ('Very good')
INSERT INTO CONDITION (CONDITION) VALUES ('Good')
INSERT INTO CONDITION (CONDITION) VALUES ('Fair')
INSERT INTO CONDITION (CONDITION) VALUES ('Worn')
INSERT INTO CONDITION (CONDITION) VALUES ('Poor')
INSERT INTO CONDITION (CONDITION) VALUES ('Very poor')
INSERT INTO CONDITION (CONDITION) VALUES ('For scrapping')

--insert into roles table
INSERT INTO ROLE (ROLE) VALUES ('Admin')
INSERT INTO ROLE (ROLE) VALUES ('Operator')
INSERT INTO ROLE (ROLE) VALUES ('Reader')

--insert into ratings table
INSERT INTO RATING (RATING) VALUES (1)
INSERT INTO RATING (RATING) VALUES (2)
INSERT INTO RATING (RATING) VALUES (3)
INSERT INTO RATING (RATING) VALUES (4)
INSERT INTO RATING (RATING) VALUES (5)

--insert into accounts table
INSERT INTO ACCOUNTS(FIRSTNAME, LASTNAME, UCN, PHONENUMBER, EMAIL, ADDRESS, USERNAME, PASSWORD, ROLE_ID, RATING_ID) 
VALUES('Daniel', 'Kostov', '3214124' , '0887565656', 'kostov@gmail.com', 'ul. Kaloqnski 5', 'slayer55', 'bibli22', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Admin'), (SELECT RATING.ID FROM RATING WHERE RATING = 5))

INSERT INTO ACCOUNTS(FIRSTNAME, LASTNAME, UCN, PHONENUMBER, EMAIL, ADDRESS, USERNAME, PASSWORD, ROLE_ID, RATING_ID) 
VALUES('Boris', 'Petrov', '0123923' , '0889232323', 'borisp@abv.bg', 'ul. Smolensk 2', 'borkata55', 'chitatelq77', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Operator'), (SELECT RATING.ID FROM RATING WHERE RATING = 5))

INSERT INTO ACCOUNTS(FIRSTNAME, LASTNAME, UCN, PHONENUMBER, EMAIL, ADDRESS, USERNAME, PASSWORD, ROLE_ID, RATING_ID) 
VALUES('Valentina', 'Naidenova', '987222' , '0887888888', 'v.naid@abv.bg', 'ul. Sv. Petka', 'v.naidenova', 'vn1990biblioteka', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Reader'), (SELECT RATING.ID FROM RATING WHERE RATING = 4))

INSERT INTO ACCOUNTS(FIRSTNAME, LASTNAME, UCN, PHONENUMBER, EMAIL, ADDRESS, USERNAME, PASSWORD, ROLE_ID, RATING_ID) 
VALUES('Ivan', 'Ivanov', '43546456' , '0889889898', 'vanko@mail.bg', 'ul. Vqrna 11', 'vankata96', 'vankosumve1', (SELECT ROLE.ID FROM ROLE WHERE ROLE.ROLE = 'Reader'), (SELECT RATING.ID FROM RATING WHERE RATING = 3))

--Insert into books table
INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVAILABLE)
VALUES ('Vlastelina na prustenite', 'G.R.R. Tolkien', 'Fantasy', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'Very good'), 'true')

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVAILABLE)
VALUES ('Pesen za ogun i led', 'G.R.R. Martin', 'Fantasy', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'Fair'), 'false')

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVAILABLE)
VALUES ('Pod igoto', 'Ivan Vazov', 'Roman', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'As new'), 'false')

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, CONDITION_ID, AVAILABLE)
VALUES ('Tobacco', 'Dimitar Dimov', 'Roman', (SELECT ID FROM CONDITION WHERE CONDITION.CONDITION = 'Worn'), 'true')

--insert into issues table
INSERT INTO ISSUE (BOOK_ID, ACCOUNT_ID, ISSUE_DATE, RETURN_DATE, RETURNED_CONDITION_ID) 
VALUES ((SELECT ID FROM BOOKS WHERE TITLE = 'Pod Igoto'), (SELECT ID FROM ACCOUNTS WHERE USERNAME = 'slayer55'), getdate(), convert(date,'15-12-20',5), (SELECT ID FROM CONDITION WHERE CONDITION = 'As new'))

INSERT INTO ISSUE (BOOK_ID, ACCOUNT_ID, ISSUE_DATE, RETURN_DATE, RETURNED_CONDITION_ID) 
VALUES ((SELECT ID FROM BOOKS WHERE TITLE = 'Pesen za ogun i led'), (SELECT ID FROM ACCOUNTS WHERE USERNAME = 'vankata96'), getdate(), convert(date,'11-12-20',5), (SELECT ID FROM CONDITION WHERE CONDITION = 'Fair'))